spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.129.130:8848
      discovery:
        server-addr: 192.168.129.130:8848

logging:
  level:
    root: warn
    com.spring.boot: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /app/logs/app.log
  logback:
    rolling-policy:
      max-file-size: 100MB
      max-history: 7

knife4j:
  production: true