spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_service_project
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

jwt:
  secret: integration-test-secret-key-2026-integration
  access-expire: 900000
  refresh-expire: 604800000