logging:
  level:
    root: info
    com.spring.boot.gateway: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

knife4j:
  production: false

jwt:
  secret: dev-local-jwt-secret-key-2026!!!