logging:
  level:
    root: info
    com.spring.boot.gateway: info
    org.springframework.cloud.gateway: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /var/log/gateway/app.log
  logback:
    rolling-policy:
      max-file-size: 50MB
      max-history: 3

knife4j:
  production: false

jwt:
  secret: test-local-jwt-secret-key-2026!!